### PR TITLE
Feature/issue 22 - Score Calculation

### PR DESCRIPTION
**Pull request by Harjun751**
Implements #22

### CODE REVIEW

**Review by jolenecpn — COMMENTED** [review]
took a look and there are minor changes to be made: 

1. FAC does not meet the sub-requirement where 5th FAC onwards score 1 point, so 4+4+4+4+1+1+...

2. for the SHP unique_building list, do add "MON" and "PRK" as well 

3. I think it's a good idea to not print the "0"s when looking at current scores but may need to review with the team 

Screenshot (618)

**Comment by Harjun751** [comment]
Thanks for checking! I'll update the code to reflect 1. & 2.

I'll also check out 3. - I didn't expect the function to behave like that.

**Comment by Harjun751** [comment]
Updated the code to account for the new buildings for SHP and factory score. Also updated the building display so that the "0"s are not shown in the calculation. For a lone house in the board it looks like this:
image
I think it looks better and makes more sense, but if we want the previous one I could revert back to that.

**Review by jolenecpn — APPROVED** [review]
the code looks good to merge

I think we should stick to this current score display cause it looks better and cleaner

**Pull request merged**
