### PR TITLE
Add CICD Using QA Repo

### PR DESCRIPTION
**Pull request by notyumin**
Key features:
- Code cov using pytester-cov on push to main
- Release using create-release on tag of "v*"

### CODE REVIEW

**Comment by Harjun751** [comment]
image
I think there's no need to lint at the start using flake8 since we're linting at the bottom using flake8.

Also the 2 workflow files CD & CI - QA seem to be the same file for different triggers? Maybe we could remove the CD one since that one triggers on tag, while the CI - QA one triggers on any push to main. Seems to me that it'll trigger both if it gets tagged. Correct me if I'm wrong tho

**Comment by notyumin** [comment]
> image I think there's no need to lint at the start using flake8 since we're linting at the bottom using flake8.
> 
> Also the 2 workflow files CD & CI - QA seem to be the same file for different triggers? Maybe we could remove the CD one since that one triggers on tag, while the CI - QA one triggers on any push to main. Seems to me that it'll trigger both if it gets tagged. Correct me if I'm wrong tho

Thanks for the comments Arjun, I'll take a look and make any necessary changes

**Comment by notyumin** [comment]
> image I think there's no need to lint at the start using flake8 since we're linting at the bottom using flake8.
> 
> Also the 2 workflow files CD & CI - QA seem to be the same file for different triggers? Maybe we could remove the CD one since that one triggers on tag, while the CI - QA one triggers on any push to main. Seems to me that it'll trigger both if it gets tagged. Correct me if I'm wrong tho

Hi Arjun, regarding the first point, I assume you mean we're using Black at the bottom to format? Linting and Formatting are slightly different so I think it's ok to keep both.

As for the second issue, the CD file is different only in 1 aspect, which is it creates a Release. Also, from what I've read, git pushing tags is separate from git pushing to a branch, so it shouldn't overlap. 

Thanks for the feedback! If my answers satisfy you, I'll go ahead and complete the pull request.

**Comment by Harjun751** [comment]
Thanks for the response - I thought linting and formatting were interchangeable terms and meant to say black at the bottom 😅.

Apparently a tag push is still considered a push to github actions. Maybe we could use an if conditional to check if there is a tag in the push and then trigger a release? Related: https://github.community/t/trigger-job-on-tag-push-only/18076/2

Anyway I was only suggesting this because it seems like there's a lot of code duplication. Idt it's a big problem though, so I'll just approve

**Review by Harjun751 — APPROVED** [review]

**Comment by notyumin** [comment]
> Thanks for the response - I thought linting and formatting were interchangeable terms and meant to say black at the bottom 😅.
> 
> Apparently a tag push is still considered a push to github actions. Maybe we could use an if conditional to check if there is a tag in the push and then trigger a release? Related: https://github.community/t/trigger-job-on-tag-push-only/18076/2
> 
> Anyway I was only suggesting this because it seems like there's a lot of code duplication. Idt it's a big problem though, so I'll just approve

Thanks for pointing that out, I have added "tags-ignore" to the CI file to avoid the CI running on tag push:
```
on:
  push:
    branches: [main]
    tags-ignore:
      - "v*"
```

**Pull request merged**
