### PR TITLE
Feature/issue 21 16

### PR DESCRIPTION
**Pull request by jolenecpn**
do review and provide feedback if there are areas to improve on :)

### CODE REVIEW

**Comment by Harjun751** [comment]
The high score section prompts for a name and the new high scores are shown, but it doesn't seem to actually save to the file. The load_game section also seems to be broken - it's saying "No game saved" but I have a save file.

The code also seems to be copied over multiple times, there are duplicates of the same function in the code. I think you need to check the conflict management when you pull. 

The isHigher function I think  could also be improved. Currently the efficiency is O(N^2) since you're iterating through the list in a loop of the same list. I think using a while loop with an index variable would be better. That way you don't need to re-check the position of the current item.

Lastly, I don't think you should use the sorted() function in isHigher. According to the specification, "if a player's score is equal to another score that  is already on the board, the new score is considered lower". I *think* the sorted function might change the order.

**Comment by jolenecpn** [comment]
1. bug fixed, should be working now, added save in function too (must have forgotten about that haha)

2. okay I'll take a look

3. good idea, will implement that in next commit, I'm thinking of putting everything into the end_game function since putting them into 2 separate functions (isHigher and end_game) may seem unnecessary 

4. hmm I don't think sorted() will affect the order, cause here's the input of the new highscore (excuse the wrong position stated, will fixed it when implementing the while loop
Screenshot (633)
)

**Comment by jolenecpn** [comment]
made the changes as per discussed above, do review thanks!

**Comment by Harjun751** [comment]
The game seems to end prematurely by one turn:
image

Additionally, the duplicated code is still there:
image

Other than that, looks fine.

**Comment by jolenecpn** [comment]
whoops must have missed that, gimme a moment

**Comment by jolenecpn** [comment]
changed isFull function, game should end as expected. Have deleted the duplicate lines of code/functions as well, do review! thanks

**Comment by Harjun751** [comment]
The program looks good to me, but update the CI file before merging

**Review by Harjun751 — APPROVED** [review]

**Comment by jolenecpn** [comment]
updated CI, shall commence merging

**Comment by jolenecpn** [comment]
updated ci and all checks passed, commencing merging of PR

**Pull request merged**
